### ISSUE TITLE
Nmap build issue after svn up -r38560

### ISSUE THREAD

**Issue by benpratt** [nmap/nmap#2568]
After @bonsaiviking commit making changes to osscan.cc and osscan.h Nmap errors during gmake (on FreeBSD) and make (on Kali Linux). Both OSes are fully updated.

Here's the error from Kali:

`g++ -c -I./liblinear -I./liblua -I./libdnet-stripped/include -I./libssh2/include -I./libpcre  -I./nbase -I./nsock/include -DHAVE_CONFIG_H -DNMAP_PLATFORM=\"x86_64-unknown-linux-gnu\" -DNMAPDATADIR=\"/usr/local/share/nmap\" -D_FORTIFY_SOURCE=2 -g -O2 -Wall -fno-strict-aliasing   osscan.cc -o osscan.o
In file included from /usr/include/c++/12/map:60,
                 from osscan.h:70,
                 from osscan.cc:66:
/usr/include/c++/12/bits/stl_tree.h: In instantiation of ‘static const _Key& std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_S_key(_Const_Link_type) [with _Key = const FingerTest*; _Val = const FingerTest*; _KeyOfValue = std::_Identity<const FingerTest*>; _Compare = FingerTestCmp; _Alloc = std::allocator<const FingerTest*>; _Const_Link_type = const std::_Rb_tree_node<const FingerTest*>*]’:
/usr/include/c++/12/bits/stl_tree.h:2117:47:   required from ‘std::pair<std::_Rb_tree_node_base*, std::_Rb_tree_node_base*> std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_get_insert_unique_pos(const key_type&) [with _Key = const FingerTest*; _Val = const FingerTest*; _KeyOfValue = std::_Identity<const FingerTest*>; _Compare = FingerTestCmp; _Alloc = std::allocator<const FingerTest*>; key_type = const FingerTest*]’
/usr/include/c++/12/bits/stl_tree.h:2170:4:   required from ‘std::pair<std::_Rb_tree_iterator<_Val>, bool> std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_insert_unique(_Arg&&) [with _Arg = const FingerTest*; _Key = const FingerTest*; _Val = const FingerTest*; _KeyOfValue = std::_Identity<const FingerTest*>; _Compare = FingerTestCmp; _Alloc = std::allocator<const FingerTest*>]’
/usr/include/c++/12/bits/stl_set.h:521:25:   required from ‘std::pair<typename std::_Rb_tree<_Key, _Key, std::_Identity<_Tp>, _Compare, typename __gnu_cxx::__alloc_traits<_Allocator>::rebind<_Key>::other>::const_iterator, bool> std::set<_Key, _Compare, _Alloc>::insert(value_type&&) [with _Key = const FingerTest*; _Compare = FingerTestCmp; _Alloc = std::allocator<const FingerTest*>; typename std::_Rb_tree<_Key, _Key, std::_Identity<_Tp>, _Compare, typename __gnu_cxx::__alloc_traits<_Allocator>::rebind<_Key>::other>::const_iterator = std::_Rb_tree<const FingerTest*, const FingerTest*, std::_Identity<const FingerTest*>, FingerTestCmp, std::allocator<const FingerTest*> >::const_iterator; typename __gnu_cxx::__alloc_traits<_Allocator>::rebind<_Key>::other = std::allocator<const FingerTest*>; typename __gnu_cxx::__alloc_traits<_Allocator>::rebind<_Key> = __gnu_cxx::__alloc_traits<std::allocator<const FingerTest*>, const FingerTest*>::rebind<const FingerTest*>; typename _Allocator::value_type = const FingerTest*; value_type = const FingerTest*]’
osscan.cc:728:21:   required from here
/usr/include/c++/12/bits/stl_tree.h:770:15: error: static assertion failed: comparison object must be invocable as const
  770 |               is_invocable_v<const _Compare&, const _Key&, const _Key&>,
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/12/bits/stl_tree.h:770:15: note: ‘std::is_invocable_v<const FingerTestCmp&, const FingerTest* const&, const FingerTest* const&>’ evaluates to false
make: *** [Makefile:119: osscan.o] Error 1
`

To reproduce, in Nmap directory run:

1. make distclean
2. svn up -r38560
3. ./configure
4. make

**Comment by jospezial** [comment]
Same in Gentoo linux with the live ebuild.

**Comment by jospezial** [comment]
The issue was introduced by https://github.com/nmap/nmap/commit/56f59de131e1bc2ff71053daa936844640f1aa96
The parent builds without that error.

**Comment by benpratt** [comment]
Over the weekend the update 024f1fe (also svn up -r38568) resolved the issue.
