### ISSUE TITLE
Compile fails in nmap_tty.cc

### ISSUE THREAD

**Issue by djcater** [nmap/nmap#1887]
```
g++ -c -I./libdnet-stripped/include  -I./nbase -I./nsock/include -DHAVE_CONFIG_H -DNMAP_PLATFORM=\"x86_64-unknown-linux-gnu\" -DNMAPDATADIR=\"/usr/local/share/nmap\" -D_FORTIFY_SOURCE=2 -g -O2 -Wall -fno-strict-aliasing   nmap_tty.cc -o nmap_tty.o
nmap_tty.cc: In function ‘void tty_init()’:
nmap_tty.cc:295:40: error: ‘O_RDONLY’ was not declared in this scope
  295 |         if ((tty_fd = open("/dev/tty", O_RDONLY | O_NONBLOCK)) < 0) return;
      |                                        ^~~~~~~~
nmap_tty.cc:295:51: error: ‘O_NONBLOCK’ was not declared in this scope; did you mean ‘SOCK_NONBLOCK’?
  295 |         if ((tty_fd = open("/dev/tty", O_RDONLY | O_NONBLOCK)) < 0) return;
      |                                                   ^~~~~~~~~~
      |                                                   SOCK_NONBLOCK
nmap_tty.cc:295:23: error: ‘open’ was not declared in this scope; did you mean ‘popen’?
  295 |         if ((tty_fd = open("/dev/tty", O_RDONLY | O_NONBLOCK)) < 0) return;
      |                       ^~~~
      |                       popen
make: *** [Makefile:120: nmap_tty.o] Error 1
```

This is with the latest commit cloned from GitHub just now (https://github.com/nmap/nmap/commit/ae10c8a19d7274979ce8073ebc7715142420bd42).

I haven't compiled from trunk for a couple of months so I'm not sure when it broke.

This is on Ubuntu 19.10, with the following commands:
```
./configure --prefix=/usr/local
make
```

GCC version: `g++ (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008`

I have compiled Nmap successfully on this machine before.

**Comment by wleborgne** [comment]
Same result on Ubuntu 18.04, after
```
./compile
make
```

compiler version `g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0`

```
g++ -c -I./liblinear -I./liblua -I./libdnet-stripped/include -I./libssh2/include  -I./nbase -I./nsock/include -DHAVE_CONFIG_H -DNMAP_PLATFORM=\"x86_64-unknown-linux-gnu\" -DNMAPDATADIR=\"/usr/local/share/nmap\" -D_FORTIFY_SOURCE=2 -g -O2 -Wall -fno-strict-aliasing   nmap_tty.cc -o nmap_tty.o
nmap_tty.cc: In function ‘void tty_init()’:
nmap_tty.cc:295:40: error: ‘O_RDONLY’ was not declared in this scope
         if ((tty_fd = open("/dev/tty", O_RDONLY | O_NONBLOCK)) < 0) return;
                                        ^~~~~~~~
nmap_tty.cc:295:40: note: suggested alternative: ‘STA_RONLY’
         if ((tty_fd = open("/dev/tty", O_RDONLY | O_NONBLOCK)) < 0) return;
                                        ^~~~~~~~
                                        STA_RONLY
nmap_tty.cc:295:51: error: ‘O_NONBLOCK’ was not declared in this scope
         if ((tty_fd = open("/dev/tty", O_RDONLY | O_NONBLOCK)) < 0) return;
                                                   ^~~~~~~~~~
nmap_tty.cc:295:51: note: suggested alternative: ‘SOCK_NONBLOCK’
         if ((tty_fd = open("/dev/tty", O_RDONLY | O_NONBLOCK)) < 0) return;
                                                   ^~~~~~~~~~
                                                   SOCK_NONBLOCK
nmap_tty.cc:295:23: error: ‘open’ was not declared in this scope
         if ((tty_fd = open("/dev/tty", O_RDONLY | O_NONBLOCK)) < 0) return;
                       ^~~~
nmap_tty.cc:295:23: note: suggested alternative: ‘popen’
         if ((tty_fd = open("/dev/tty", O_RDONLY | O_NONBLOCK)) < 0) return;
                       ^~~~
                       popen
Makefile:120: recipe for target 'nmap_tty.o' failed
make: *** [nmap_tty.o] Error 1
```
Looks like it's the latest commit; I also had a several month old clone, and tried `git bisect`, which brought me right back to `ae10c8a19`. No build problems with `a2c75e0ef`.

**Comment by djcater** [comment]
Thanks for confirming!

Adding back the `#include <nbase.h>` to nmap.h was enough to fix it for me (although there may be a better solution).

Paging @bonsaiviking / @dmiller-nmap.

**Comment by dmiller-nmap** [comment]
Thanks! Turns out we had some missing header checks that were being hidden by the inclusion of nbase.h. Fix incoming.

**Comment by djcater** [comment]
I just did a fresh clone and then `configure` and `make` worked fine. Thanks!

**Comment by dmiller-nmap** [comment]
Glad to hear it! Closing.
