### ISSUE TITLE
Nmap 7.93 fails to build on OS X against libressl 3.6.2

### ISSUE THREAD

**Issue by udf2457** [nmap/nmap#2612]
Mac OS X Ventura 13.2 on Apple Silicon (M2)

Downloaded libressl-3.6.2 and compiled against  local dir (`configure --prefix=/path/to/build_dir`)
Downloaded nmap-7.93 and tried to compile against same dir (`configure --prefix=/path/to/build_dir --with-openssl=/path/to/build_dir)

Result:
```
crypt.c:71:25: error: field has incomplete type 'EVP_CIPHER_CTX' (aka 'struct evp_cipher_ctx_st')
    _libssh2_cipher_ctx h;
                        ^
/path/to/build_dir/include/openssl/ossl_typ.h:118:16: note: forward declaration of 'struct evp_cipher_ctx_st'
typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX;
               ^
1 error generated.
make[2]: *** [crypt.lo] Error 1
make[1]: *** [all] Error 2
make: *** [build-libssh2] Error 2
```

**Comment by YLSnewb** [comment]
nmap 7.93 fails with identical error with LibreSSL 3.7.2 on Mac OS X Ventura 13.3+.

**Comment by TheProdigyLeague** [comment]
@udf2457 
@YLSnewb 
By no means, do I have oversight on these projects...
However, after brief researching:
It looks like improper machine handling of String Compiler...("Or whatever Compiler this build is run");
Therefore, your machine may be Throwing this "Forward Declaration" string issue due to defected Code. Or, maybe, deprecated Crypto...
Below, I have annotated the issue:
>>> from Crypto.c in fs.config --prefix=/path/to/build_dir
>>> from Crypto.c in fs.config --prefix=/path/to/build_dir --with-openssl=/path/to/build_dir
>>> in crypt.c(++) c:71, l:25: throw this $echo_in c.bat "ERROR, FIELD HAS INCOMPLETE TYPE 'EVP_CIPHER_CTX' (a.k.a 'struct *evp_cipher_ctx_st')_libssh2_cipher_ctx.h; ";;
$$_/path/to/build_dir/include/openssl/ossl_typ.h:118:16
ERROR "String field has incomplete type script from enveloped Ciphon NYSE: CTX "
:root_/path/build/dir/include.lua
:root_/openssl/ossl_type.h
Continue
~
    # note://forward declaration of 'struct evp_cipher_ctx_st' 
>>> from
        { "1 | ERR_GEN "};
>>> docker makefile in ARR [1]: '&&' ARR [2]: usr***ARR+[crypt.lo]: err in 1, [all]: err in 2 [build-libssh2]: err in 3
return value COMPILER ERROR,
==$0
// C envelops NYSE: the Ctx_hex into Ctx_Key from ctx_"algorithm" By Author(cTM)OpenSSL fs.bat fs.dat 
// the machine node string hex comes from a bogus token

**Comment by YLSnewb** [comment]
> Or, maybe, deprecated Crypto...

LibreSSL 3.7.2 is current as of my report.  Unless you mean that nmap is using a deprecated call.

**Comment by theoparis** [comment]
I encountered the same issue with MacOS Tahoe on a M2 Macbook with the latest Libressl 👀  Additionally, I got similar errors with X509 and RSA

## Error Log
```
g++ -c -I./liblinear -I./liblua -I./libdnet-stripped/include -I./libssh2/include -I./libpcre/src  -I./libpcap -I./nbase -I./nsock/include -DHAVE_CONFIG_H -DNMAP_PLATFORM=\"arm-apple-darwin25.0.0\" -DNMAPDATADIR=\"/usr/local/share/nmap\" -D_FORTIFY_SOURCE=2 -no-cpp-precomp -g -O2 -Wall -fno-strict-aliasing   main.cc -o main.o
nse_ssl_cert.cc:494:36: error: use of undeclared identifier 'EC_GROUP_method_of'
  494 |     nid = EC_METHOD_get_field_type(EC_GROUP_method_of(group));
      |                                    ^
nse_ssl_cert.cc:573:53: error: member access into incomplete type 'X509' (aka 'x509_st')
  573 |   const char *sig_algo = OBJ_nid2ln(OBJ_obj2nid(cert->sig_alg->algorithm));
      |                                                     ^
/usr/local/include/openssl/ossl_typ.h:142:16: note: forward declaration of 'x509_st'
  142 | typedef struct x509_st X509;
      |                ^
nse_ssl_cert.cc:593:39: error: member access into incomplete type 'X509' (aka 'x509_st')
  593 |   if (x509_extensions_to_table(L, cert->cert_info->extensions)) {
      |                                       ^
/usr/local/include/openssl/ossl_typ.h:142:16: note: forward declaration of 'x509_st'
  142 | typedef struct x509_st X509;
      |                ^
nse_ssl_cert.cc:610:35: error: member access into incomplete type 'EVP_PKEY' (aka 'evp_pkey_st')
  610 |   pkey_type = EVP_PKEY_type(pubkey->type);
      |                                   ^
/usr/local/include/openssl/ossl_typ.h:116:16: note: forward declaration of 'evp_pkey_st'
  116 | typedef struct evp_pkey_st EVP_PKEY;
      |                ^
nse_ssl_cert.cc:643:19: error: member access into incomplete type 'RSA' (aka 'rsa_st')
  643 |     nse_pushbn(L, PASS_RSA_PARAM(e), should_free);
      |                   ^
nse_ssl_cert.cc:640:33: note: expanded from macro 'PASS_RSA_PARAM'
  640 | # define PASS_RSA_PARAM(_P) (rsa->_P)
      |                                 ^
/usr/local/include/openssl/ossl_typ.h:136:16: note: forward declaration of 'rsa_st'
  136 | typedef struct rsa_st RSA;
      |                ^
nse_ssl_cert.cc:646:19: error: member access into incomplete type 'RSA' (aka 'rsa_st')
  646 |     nse_pushbn(L, PASS_RSA_PARAM(n), should_free);
      |                   ^
nse_ssl_cert.cc:640:33: note: expanded from macro 'PASS_RSA_PARAM'
  640 | # define PASS_RSA_PARAM(_P) (rsa->_P)
      |                                 ^
/usr/local/include/openssl/ossl_typ.h:136:16: note: forward declaration of 'rsa_st'
  136 | typedef struct rsa_st RSA;
      |                ^
6 errors generated.
make: *** [nse_ssl_cert.o] Error 1
make: *** Waiting for unfinished jobs....
nse_openssl.cc:399:18: error: variable has incomplete type 'EVP_CIPHER_CTX' (aka 'evp_cipher_ctx_st')
  399 |   EVP_CIPHER_CTX stack_ctx;
      |                  ^
/usr/local/include/openssl/ossl_typ.h:113:16: note: forward declaration of 'evp_cipher_ctx_st'
  113 | typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX;
      |                ^
nse_openssl.cc:461:18: error: variable has incomplete type 'EVP_CIPHER_CTX' (aka 'evp_cipher_ctx_st')
  461 |   EVP_CIPHER_CTX stack_ctx;
      |                  ^
/usr/local/include/openssl/ossl_typ.h:113:16: note: forward declaration of 'evp_cipher_ctx_st'
  113 | typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX;
      |                ^
2 errors generated.
make: *** [nse_openssl.o] Error 1
```
