### ISSUE TITLE
[build] nmap 7.94 failed to build with lua 5.4.6

### ISSUE THREAD

**Issue by chenrui333** [nmap/nmap#2648]
Got some weird build error while trying to [upgrade nmap formula to 7.94](https://github.com/Homebrew/homebrew-core/pull/131512):

```
  clang++ -c -I/usr/local/opt/lua/include -I./libdnet-stripped/include -I/usr/local/opt/pcre/include  -I/usr/local/opt/openssl@1.1/include -I./nbase -I./nsock/include -DHAVE_CONFIG_H -DNMAP_PLATFORM=\"x86_64-apple-darwin21.6.0\" -DNMAPDATADIR=\"/usr/local/Cellar/nmap/7.94/share/nmap\" -D_FORTIFY_SOURCE=2 -no-cpp-precomp -I/usr/local/opt/lua/include/lua -Wall -fno-strict-aliasing   FingerPrintResults.cc -o FingerPrintResults.o
  In file included from FingerPrintResults.cc:65:
  In file included from ./NmapOps.h:68:
  In file included from ./output.h:106:
  ./nse_main.h:25:26: error: unknown type name 'lua_State'
      void set_output_tab (lua_State *, int);
                           ^
  ./nse_main.h:19:43: error: use of undeclared identifier 'LUA_NOREF'
      ScriptResult() : id(NULL), output_ref(LUA_NOREF) {}
                                            ^
  ./nse_main.h:44:16: error: unknown type name 'lua_State'
  int nse_yield (lua_State *, lua_KContext, lua_KFunction);
                 ^
  ./nse_main.h:44:29: error: unknown type name 'lua_KContext'
  int nse_yield (lua_State *, lua_KContext, lua_KFunction);
                              ^
  ./nse_main.h:44:43: error: unknown type name 'lua_KFunction'
  int nse_yield (lua_State *, lua_KContext, lua_KFunction);
                                            ^
  ./nse_main.h:45:19: error: unknown type name 'lua_State'
  void nse_restore (lua_State *, int);
                    ^
  ./nse_main.h:46:22: error: unknown type name 'lua_State'
  void nse_destructor (lua_State *, char);
                       ^
  ./nse_main.h:47:16: error: unknown type name 'lua_State'
  void nse_base (lua_State *);
                 ^
  ./nse_main.h:48:26: error: unknown type name 'lua_State'
  void nse_selectedbyname (lua_State *);
                           ^
  ./nse_main.h:49:21: error: unknown type name 'lua_State'
  void nse_gettarget (lua_State *, int);
                      ^
  10 errors generated.
  make: *** [FingerPrintResults.o] Error 1
```

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/5043025863/jobs/9044435033

**Comment by carlocab** [comment]
Setting `-DHAVE_LUA5_4_LUA_H` works around this problem, but it seems like this is something that should be handled by `configure`. Indeed, I see it defined in `config.log`, but the definitions there don't make it to the compiler invocation for some reason.

**Comment by carlocab** [comment]
For easy reference: [logs.tar.gz](https://github.com/nmap/nmap/files/11542421/logs.tar.gz)

After extracting, you can find `config.log` (for example) at `logs-*/nmap/config.log`.
