### ISSUE TITLE
[fixed] Compilation error in libpcap: "No rule to make target '../libpcap/pcap/export-defs.h', needed by 'netutil.o'"

### ISSUE THREAD

**Issue by cnotin** [nmap/nmap#1558]
EDIT: the problem is gone after cleaning the repository (`git clean -fx`, yes I know I use git...). It seems that the references to "export-defs.h" remained in makefile.dep and other files, even after `make clean`
I keep the issue open if an improvement of the Makefile is maybe required

Since a2442ea29fb5f8e67c8dba1a68a4a3377ff4dea3 (confirmed with a git bisect) I have problems compiling the source code (from Kali).
```terminal
# make clean && ./configure && make -j8 && ./nmap
[...]
Compiling libnetutil
cd libnetutil && make
Compiling liblinear
make[1]: Entering directory '/root/tools/nmap/liblinear'
make[1]: 'liblinear.a' is up to date.
make[1]: Leaving directory '/root/tools/nmap/liblinear'
make[1]: Entering directory '/root/tools/nmap/libnetutil'
make[1]: *** No rule to make target '../libpcap/pcap/export-defs.h', needed by 'netutil.o'.  Stop.
make[1]: Leaving directory '/root/tools/nmap/libnetutil'
Compiling libssh2
make: *** [Makefile:163: build-netutil] Error 2
make: *** Waiting for unfinished jobs....
make[1]: Entering directory '/root/tools/nmap/libssh2/src'
[...]
```

The error seems to be:
```
No rule to make target '../libpcap/pcap/export-defs.h', needed by 'netutil.o'.  Stop.
```

The problem is still present in the latest commit (85ec647932a9c7ec3c84f12e6da8ebe935e70de8)

I see that this file was deleted:
https://github.com/nmap/nmap/commit/a2442ea29fb5f8e67c8dba1a68a4a3377ff4dea3#diff-e423e151d60ffb1f32b8ca981135a0c9

**Comment by cnotin** [comment]
I see that this file was deleted:
https://github.com/nmap/nmap/commit/a2442ea29fb5f8e67c8dba1a68a4a3377ff4dea3#diff-e423e151d60ffb1f32b8ca981135a0c9

**Comment by dmiller-nmap** [comment]
`makefile.dep` is only removed with `make distclean`, not `make clean`. If you can reproduce the problem and it is not solved by `make distclean`, then we will reopen this issue. Thanks!

**Comment by cnotin** [comment]
I confirm, my bad I'm not very good with automake :)
