### ISSUE TITLE
Nping fails to compile

### ISSUE THREAD

**Issue by dragonxtek** [nmap/nmap#1278]
I configure nmap without issues, but I got the following message after execute make:

> Compiling nping
rm -f nping
g++   -o nping ArgParser.o common.o common_modified.o nping.o NpingOps.o utils.o utils_net.o output.o stats.o NpingTargets.o NpingTarget.o EchoHeader.o EchoServer.o EchoClient.o ProbeMode.o NEPContext.o Crypto.o ../nsock/src/libnsock.a ../nbase/libnbase.a ../libnetutil/libnetutil.a -lssl -lcrypto -lpcap ../libdnet-stripped/src/.libs/libdnet.a -ldl 
../nsock/src/libnsock.a(nsock_core.o): In function `handle_connect_result':
/tmp/nmap/nsock/src/nsock_core.c:451: undefined reference to `SSL_get_options'
/tmp/nmap/nsock/src/nsock_core.c:487: undefined reference to `SSL_set_options'
Crypto.o: In function `Crypto::aes128_cbc_encrypt(unsigned char*, unsigned long, unsigned char*, unsigned char*, unsigned long, unsigned char*)':
/tmp/nmap/nping/Crypto.cc:209: undefined reference to `EVP_CIPHER_CTX_reset'
/tmp/nmap/nping/Crypto.cc:222: undefined reference to `EVP_CIPHER_CTX_reset'
Crypto.o: In function `Crypto::aes128_cbc_decrypt(unsigned char*, unsigned long, unsigned char*, unsigned char*, unsigned long, unsigned char*)':
/tmp/nmap/nping/Crypto.cc:248: undefined reference to `EVP_CIPHER_CTX_reset'
/tmp/nmap/nping/Crypto.cc:286: undefined reference to `EVP_CIPHER_CTX_reset'
Crypto.o: In function `Crypto::deriveKey(unsigned char const*, unsigned long, unsigned long*)':
/tmp/nmap/nping/Crypto.cc:324: undefined reference to `EVP_MD_CTX_new'
/tmp/nmap/nping/Crypto.cc:328: undefined reference to `EVP_MD_CTX_reset'
/tmp/nmap/nping/Crypto.cc:340: undefined reference to `EVP_MD_CTX_reset'
/tmp/nmap/nping/Crypto.cc:349: undefined reference to `EVP_MD_CTX_reset'
../nsock/src/libnsock.a(nsock_ssl.o): In function `nsock_pool_ssl_init_helper':
/tmp/nmap/nsock/src/nsock_ssl.c:137: undefined reference to `SSL_CTX_clear_options'
/tmp/nmap/nsock/src/nsock_ssl.c:138: undefined reference to `SSL_CTX_set_options'
/tmp/nmap/nsock/src/nsock_ssl.c:137: undefined reference to `SSL_CTX_clear_options'
/tmp/nmap/nsock/src/nsock_ssl.c:138: undefined reference to `SSL_CTX_set_options'
../nsock/src/libnsock.a(nsock_ssl.o): In function `ssl_init_common':
/tmp/nmap/nsock/src/nsock_ssl.c:109: undefined reference to `TLS_client_method'
../nsock/src/libnsock.a(nsock_ssl.o): In function `nsock_pool_dtls_init':
/tmp/nmap/nsock/src/nsock_ssl.c:175: undefined reference to `SSL_CTX_clear_options'
collect2: error: ld returned 1 exit status
Makefile:87: recipe for target 'nping' failed
make[1]: *** [nping] Error 1
make[1]: Leaving directory '/tmp/nmap/nping'
Makefile:84: recipe for target 'all' failed
make: *** [all] Error 2

I have Ubuntu 17.10 and I have the same problem with both, nmap tarball version and from github.

**Comment by drewvian** [comment]
I had almost this exact set of errors during this build, using customized Linux distro that is Gentoo based. After quite a bit of troubleshooting, the problem was having multiple versions of openssl installed. Building against OpenSSL 1.1.1 resulted in these errors. Building against OpenSSL 1.0.2p worked properly. Note that just adding the '--with-openssl=<dir>' flags did not correct this problem, because the build process was still locating some of the header files for 1.1.1. I had to uninstall OpenSSL 1.1.1 before I could get the build to function properly.

**Comment by dragonxtek** [comment]
Now I'm working with OpenSSL 3.0.0-alpha2-dev and the problem still exists.
Please fix it to avoid downgrade the openssl version.

**Comment by fyodor** [comment]
Closing this as we've upgraded our OpenSSL and related code many times since then, so we would need a new issue if this is still a problem with current Nmap.
