### ISSUE TITLE
nmap fails to compile with libressl 3.5.3 (opaque types)

### ISSUE THREAD

**Issue by kyx0r** [nmap/nmap#2484]
```
crypt.c:71:25: error: field 'h' has incomplete type
   71 |     _libssh2_cipher_ctx h;
      |                         ^
```

Some people taken a note already, but there is no working patch as far as I tried
to fix the problem by specifying a special define in libssh2/src/openssl.h 
``` # define HAVE_OPAQUE_STRUCTS 1 ```

This removes errors from libssh2 but it still failes to compile elsewhere and I
get error like:

```
nse_openssl.cc:328:14: error: aggregate 'EVP_MD_CTX mdctx' has incomplete type and cannot be defined
  328 |   EVP_MD_CTX mdctx;
```

**Comment by dmiller-nmap** [comment]
Thanks, it looks like libssh2 also applied this same change upstream, so it should be safe to make the change in our copy. We're due for an upgrade to libssh2 anyway, though 1.10.0 predates this change.

**Comment by fyodor** [comment]
We think this is resolved since we upgraded to LibSSH2 1.11.0 in Nmap Version 7.95.  If anyone still has the issue with that version, please let us know and/or re-open.  Cheers.
