### ISSUE TITLE
Update Nmap to work with OpenSSL 1.1

### ISSUE THREAD

**Issue by dmiller-nmap** [nmap/nmap#439]
OpenSSL 1.1 will be released soon, and Nmap currently fails to build with it. There are 2 parts of this task:

1. Fix the build, using preprocessor macros when necessary to ensure that it still builds with the OpenSSL 1.0.x branches.
2. Research and document any functional changes to the way Nmap does things. Issues in the past have been: removal of SSLv2, needing backwards-compatible handshake methods, addition of SNI-related calls.

References:
* [FTBFS bug on Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828454)
* [OpenSSL API changes in 1.1](https://wiki.openssl.org/index.php/1.1_API_Changes)

**Comment by W0naN0w** [comment]
Hello @dmiller-nmap, I've successfully installed OpenSSL 1.1 on both Ubuntu 14.04 and Mac OS 10.11.5. Unfortunately, it seems like some structure declarations we are currently using have been moved into the internal part of version 1.1.0-pre5. Here is an example of the errors I am encountering:
```
nse_openssl.cc:284:14: error: variable has incomplete type 'EVP_MD_CTX' (aka 'evp_md_ctx_st')
  EVP_MD_CTX mdctx;
             ^
/Users/veagle/openssl1.1-inst/include/openssl/ossl_typ.h:136:16: note: forward declaration of 'evp_md_ctx_st'
typedef struct evp_md_ctx_st EVP_MD_CTX;
```
With internal headers included directly, everything seems to work fine, but I can't figure out a way to include these the usual way (<header>). For example, I couldn't include openssl/crypto/evp/evp_locl.h (even with `#include <openssl/evp_locl.h>`) neither the internal ones.

What would be the best solution here? Import the internal headers? Maybe the openssl team is working on it and moving the proper structure declarations into the right place. 

Waiting for your comments,
Cheers

**Comment by dmiller-nmap** [comment]
Fixed in #460
